REGION_NAME="Interior Admreg"
OSM_URL="https://download.geofabrik.de/north-america/canada/british-columbia/interior-admreg-latest.osm.pbf"
FAMILY_ID="53875"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
