REGION_NAME="Southcoast Admreg"
OSM_URL="https://download.geofabrik.de/north-america/canada/british-columbia/southcoast-admreg-latest.osm.pbf"
FAMILY_ID="55126"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
