REGION_NAME="East Yorkshire with Hull"
OSM_URL="https://download.geofabrik.de/europe/united-kingdom/england/east-yorkshire-with-hull-latest.osm.pbf"
FAMILY_ID="6159"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
