REGION_NAME="Duesseldorf Regbez"
OSM_URL="https://download.geofabrik.de/europe/germany/nordrhein-westfalen/duesseldorf-regbez-latest.osm.pbf"
FAMILY_ID="40102"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
