REGION_NAME="Saint Helena, Ascension, and Tristan da Cunha"
OSM_URL="https://download.geofabrik.de/africa/saint-helena-ascension-and-tristan-da-cunha-latest.osm.pbf"
FAMILY_ID="39595"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
