REGION_NAME="Karlsruhe Regbez"
OSM_URL="https://download.geofabrik.de/europe/germany/baden-wuerttemberg/karlsruhe-regbez-latest.osm.pbf"
FAMILY_ID="60502"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
