REGION_NAME="Stuttgart Regbez"
OSM_URL="https://download.geofabrik.de/europe/germany/baden-wuerttemberg/stuttgart-regbez-latest.osm.pbf"
FAMILY_ID="10710"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
