REGION_NAME="Tuebingen Regbez"
OSM_URL="https://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez-latest.osm.pbf"
FAMILY_ID="45448"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
