REGION_NAME="Newfoundland and Labrador"
OSM_URL="https://download.geofabrik.de/north-america/canada/newfoundland-and-labrador-latest.osm.pbf"
FAMILY_ID="3756"
CONTOUR_STEP="50"
CONTOUR_LINE_CAT="500,250"
